const CATEGORY = {
  READ: 'CATEGORY.READ',
  CREATE: 'CATEGORY.CREATE',
  UPDATE: 'CATEGORY.UPDATE',
  DELETE: 'CATEGORY.DELETE'
};

const USER = {
  READ: 'USER.READ',
  READ_SELF: 'USER.READ_SELF',
  CREATE: 'USER.CREATE',
  UPDATE: 'USER.UPDATE',
  DELETE: 'USER.DELETE'
};

module.exports = {
  CATEGORY,
  USER
};